name: test
on:
  push:
    branches_ignore:
      - 'docs'
  pull_request:
    branches_ignore:
      - 'docs'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: lint
        run: |
          zig fmt --check src/
          zig fmt --check build.zig

  build-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{matrix.os}}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: build
        run: zig build

      - name: test
        run: zig build test

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: setup-git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: checkout
        uses: actions/checkout@v4

      - name: setup-zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: build
        run: |
          zig build -Dtarget=x86_64-windows --prefix tmp

      - name: test
        run: zig build test
